mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo
  - tiennou/screepsmod-map-tool#feat/resource-copy
  # - git+https://github.com/ScreepsMods/screepsmod-map-tool
  - screepsmod-history
  - screepsmod-dynamicmarket
bots:

launcherOptions:
  autoUpdate: false
  logConsole: true
  runnerCount: 10
  processorCount: 10

serverConfig:
  map: random_2x2
  tickRate: 1000
  socketUpdateRate: 1000
  whitelist:
    - D3P0
    - DroidDroid
    - Dumproni
    - Haroni
    - StageCheese
    - Jaroni_185
    - kirk
    - LordDroid
    - MadDroidM1k3
    - MIRR-E
    - mocnyDroid
    - QuanLe
    - RB-Droid
    - K2-SBense
    - Silten
    - ValhallaCalzone

  shardName: thunderdrone
  welcomeText: |
    <h1>Welcome to the <i>Thunderdrone</i></h1>
    <p>Session 3 of the Thunderdrone community event</p>
    <div>Powered by screepsmod-admin-utils</div>
  gclToCPU: true
  maxCPU: 100
  baseCPU: 20
  stepCPU: 10
